packages:
  - "apps/*"
  - "packages/*"
  - tooling/*

catalog:

  # Dev tooling
  eslint: ^9.26.0
  prettier: ^3.5.3
  tailwindcss: ^4.1.6
  typescript: ^5.8.3

  # Misc
  zod: ^3.24.4
  wrangler: "^4.14.4"

catalogs:
  react19:
    react: 19.1.0
    react-dom: 19.1.0
    "@types/react": ^19.1.2
    "@types/react-dom": ^19.1.2

